version: '3.8'

services:
  backend:
    build: ./apps/backend
    container_name: candidate-backend
    ports:
      - '3001:3001'
    networks:
      - candidate-net

  reverse-proxy:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: candidate-reverse-proxy
    depends_on:
      - backend
    ports:
      - '80:80'
    networks:
      - candidate-net

networks:
  candidate-net:
    driver: bridge
